CREATE TABLE  `newslookup_all` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(200) NOT NULL,
  `link` varchar(255) NOT NULL,
  `description` varchar(255) NOT NULL,
  `meta_keywords` varchar(255) NOT NULL,
  `meta_description` varchar(255) NOT NULL,
  `category` varchar(45) NOT NULL,
  `referrer` varchar(255) NOT NULL,
  `site_title` varchar(255) NOT NULL,
  `site_link` varchar(255) NOT NULL,
  `pubdate` varchar(45) NOT NULL,
  `image_link` varchar(255) NOT NULL,
  `geo_id` int(10) unsigned NOT NULL DEFAULT '0',
  `geo_parent` int(10) unsigned NOT NULL DEFAULT '0',
  `geo_region1` int(10) unsigned NOT NULL,
  `geo_region2` int(10) unsigned NOT NULL,
  `geo_region3` int(10) unsigned NOT NULL,
  `geo_local_db` int(10) unsigned NOT NULL,
  `geo_local_id` int(10) unsigned NOT NULL,
  `postal` int(10) unsigned NOT NULL,
  `geo_metro_db` int(10) unsigned NOT NULL,
  `geo_metro_id` int(10) unsigned NOT NULL,
  `latitude` float(10,8) DEFAULT NULL,
  `longitude` float(10,8) DEFAULT NULL,
  `media_type` int(10) unsigned NOT NULL DEFAULT '0',
  `words` longtext CHARACTER NOT NULL,
  `cache` tinyint(3) unsigned NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

